FROM dinotools/dionaea:latest
RUN apt-get update
RUN apt install vlan net-tools ethtool iproute2 iputils-ping traceroute python3 python3-pip -y
RUN apt install procps -y
RUN apt install apt-transport-https iputils-ping traceroute iproute2 -y
RUN apt install -y telnet ftp
RUN apt install -y git